name: 中国移动10086浏览器
version: 0.3.1
slug: china_mobile_browser
description: 在 HAOS 上通过浏览器登录并查询中国移动账号
url: https://github.com/cumtwjq/china-mobile-10086-ha
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: true
ingress: true
ingress_port: 6080
panel_icon: mdi:cellphone
map:
  - type: share
    read_only: false
options: {}
schema: {}
